spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - '*'
              - 'http://localhost:4200'
            allowedHeaders:
              - 'Content-Type'
            allowedMethos:
              - GET
              - POST
              - PUT
              - DELETE
