spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedHeaders:
              - Content-Type
            allowedMethos:
              - GET
              - POST
              - PUT
              - DELETE
